name: OWASP Dependency-Check

on:
  push:
    branches: ["**"]  # Run on every branch
  pull_request:
    branches: ["**"]  # Run on every PR

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set JAVA_HOME explicitly
        run: echo "JAVA_HOME=${{ steps.setup-java.outputs.JAVA_HOME }}" >> $GITHUB_ENV

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Verify JAVA_HOME
        run: echo "JAVA_HOME is set to $JAVA_HOME"

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "secure"
          path: "."
          format: "HTML"
          out: "reports"
        env:
          JAVA_HOME: ${{ github.env.JAVA_HOME }}
#          JAVA_HOME: ${{ steps.setup-java.outputs.JAVA_HOME }}  # Explicitly pass JAVA_HOME to Docker

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
