name: Java CI with Maven

on:
  push:
    branches: [ "**" ]  # Triggers on all branches
  pull_request:
    branches: [ "**" ]  # Triggers for all PRs

permissions:  # ✅ Add required permissions
  contents: read
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Verify Maven Wrapper
      run: |
        chmod +x mvnw
        ./mvnw --version

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-

    - name: Run Tests
      run: mvn test --batch-mode --fail-fast

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-jar
        path: target/*.jar
        retention-days: 7

    - name: Update Dependency Graph
      uses: advanced-security/maven-dependency-submission-action@v4
